# AI Writing Assistant Configuration File

# Server Configuration
server:
  port: 8080
  host: "0.0.0.0"

# AI Model Configuration
ai:
  # Default Model
  default_model: "deepseek"
  
  # Tongyi Configuration
  tongyi:
    api_key: "${TONGYI_API_KEY}"
    base_url: "${TONGYI_BASE_URL}"
    model: "qwen-turbo"
    max_tokens: 2000
    temperature: 0.7
  
  # DeepSeek Configuration
  deepseek:
    api_key: "sk-ec549be8267541d88f41acce65ff5f8d"
    base_url: "https://api.deepseek.com/chat/completions"
    model: "deepseek-chat"
    max_tokens: 8000
    temperature: 0.7
  
  # Wenxin Configuration
  wenxin:
    api_key: "bce-v3/ALTAK-Cdf9ftiZXfOoSsobxm2Sv/a1f7952832319e63d7b2623c5c9315a73519e2c0"
    base_url: "https://qianfan.baidubce.com/v2/chat/completions"
    model: "ERNIE 3.5"
    max_tokens: 16384
    temperature: 0.7
  
  # Zhipu AI Configuration
  zhipu:
    api_key: "${ZHIPU_API_KEY}"
    base_url: "${ZHIPU_BASE_URL}"
    model: "glm-4"
    max_tokens: 2000
    temperature: 0.7

# Database Configuration (Reserved)
database:
  driver: "sqlite"
  dsn: "./data/app.db"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout" 